copp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from django.conf import settings

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('programs/', include('edu_progs.urls', namespace='edu_progs')),
    path('news/', include('news.urls', namespace='news')),
    path('events/', include('events.urls', namespace='events')),
    path('vacancies/', include('vacancy.urls', namespace='vacancy')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

events/urls.py
from django.urls import path

from . import views

app_name = 'events'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:pk>/', views.event_detail, name='event-detail'),
]

events/models.py
from django.db import models


class Event(models.Model):
    """Мероприятие."""

    name = models.CharField(
        max_length=140,
        verbose_name='Имя мероприятия'
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание мероприятия',
        help_text='Описание мероприятия'
    )
    image = models.ImageField(
        upload_to='events/images',
        verbose_name='Изображение'
    )
    date = models.DateTimeField(
        verbose_name='Дата мероприятия',
    )
    duration = models.PositiveSmallIntegerField(
        verbose_name='Длительность мероприятия',
    )
    text = models.TextField(
        verbose_name='Подробное описание программы',
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name='Мероприятие опубликовано'
    )

    class Meta:
        verbose_name = 'Мероприятие'
        verbose_name_plural = 'Мероприятия'

    def __str__(self):
        return self.name

events/views.py
from django.shortcuts import render

from .models import Event


def index(request):
    events = Event.objects.all()

    context = {'events': events}
    return render(request, 'events/index.html', context)


def event_detail(request, pk):
    event = Event.objects.get(id=pk)
    context = {'event': event}
    return render(request, 'events/event_detail.html', context)

events/templates/events/includes/short_story.html
{% load thumbnail %}

<div class="prog_unit_sh">

    <div class="prog_image_sh">
        {% thumbnail event.image "300" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
    </div>


    <div class="card_inner_text">
        <div class="post_title">
            <a href="{% url 'events:event-detail' event.id %}">{{ event.name }}</a>
        </div>

        <div class="prog_discript_sh">
            {{ event.text | safe }}
        </div>

        <div class="start_study_sh">
            Дата мероприятия: {{ event.date }}
        </div>
    </div>


</div>