copp/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

from django.conf import settings

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('programs/', include('edu_progs.urls', namespace='edu_progs')),
    path('news/', include('news.urls', namespace='news')),
    path('events/', include('events.urls', namespace='events')),
    path('vacancies/', include('vacancy.urls', namespace='vacancy')),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

edu_progs/urls.py
from django.urls import path

from . import views

app_name = 'edu_progs'

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:pk>/', views.program_detail, name='program-detail'),
    path('form/<str:pk>/', views.program_form, name='program-form'),
    path('order-success/<str:pk>/', views.program_order_success, name='program-order-success'),
]

edu_progs/models.py
from django.contrib.auth import get_user_model
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField


User = get_user_model()


class Program(models.Model):
    """Учебная программа."""

    name = models.CharField(
        max_length=140,
        verbose_name='Имя программы'
    )
    description = models.TextField(
        null=True,
        blank=True,
        verbose_name='Описание программы',
        help_text='Описание программы'
    )
    image = models.ImageField(
        upload_to='programs/images',
        verbose_name='Изображение'
    )
    reg_start = models.DateField(
        verbose_name='Дата начала регистрации',
    )
    reg_end = models.DateField(
        verbose_name='Дата конца регистрации',
    )
    is_intramural = models.BooleanField(
        verbose_name='Очная форма',
        default=True
    )
    is_free = models.BooleanField(
        verbose_name='Бесплатная программа'
    )
    text = models.TextField(
        verbose_name='Подробное описание программы',
    )
    is_published = models.BooleanField(
        default=False,
        verbose_name='Программа опубликована'
    )

    class Meta:
        verbose_name = 'Учебная программа'
        verbose_name_plural = 'Учебные программы'

    def __str__(self):
        return self.name


class Order(models.Model):
    """Заявка на программу."""
    name = models.CharField(
        max_length=100,
        verbose_name="Имя заявителя",
        null=True
    )
    program = models.ForeignKey(
        Program,
        verbose_name="Программа в заявке",
        on_delete=models.CASCADE
    )
    phone = PhoneNumberField(
        verbose_name="Номер телефона",
        help_text="Номер телефона",
        null=False,
        blank=False
    )
    email = models.EmailField(
        verbose_name="Почта",
        max_length=254
    )
    created = models.DateTimeField(
        verbose_name='Дата заявки',
        auto_now_add=True
    )
    handled = models.DateTimeField(
        verbose_name='Дата обработки',
        null=True,
        blank=True
    )
    is_handled = models.BooleanField(
        verbose_name='Заявка обработана',
        default=False
    )
    note = models.TextField(
        verbose_name='Заметка для менеджера',
        null=True,
        blank=True
    )

    class Meta:
        verbose_name = 'Заявка на программу'
        verbose_name_plural = 'Заявки на программы'

    def __str__(self):
        return f'{self.name} {str(self.phone)} {self.email}'

edu_progs/forms.py
from django import forms
from phonenumber_field.formfields import PhoneNumberField

from .models import Order, Program


class OrderForm(forms.ModelForm):
    phone = PhoneNumberField(label='Телефон')

    class Meta:
        model = Order
        fields = ('name', 'phone', 'email')

edu_progs/views.py
from django.shortcuts import render, redirect
from django.urls import reverse

from edu_progs.forms import OrderForm
from edu_progs.models import Order, Program


def index(request):
    progs = Program.objects.all()

    context = {'progs': progs}
    return render(request, 'edu_progs/index.html', context)


def program_detail(request, pk):
    program = Program.objects.get(id=pk)
    context = {'program': program}
    return render(request, 'edu_progs/program_detail.html', context)


def program_form(request, pk):
    program = Program.objects.get(id=pk)
    form = OrderForm(request.POST or None)
    if form.is_valid():
        order = form.save(commit=False)
        order.program = program
        order.save()
        print(order.pk)
        return redirect(reverse('edu_progs:program-order-success', kwargs={'pk': order.pk}))
    context = {'program': program, 'form': form}
    return render(request, 'edu_progs/program_form.html', context)


def program_order_success(request, pk):
    order = Order.objects.get(id=pk)

    context = {'order': order}
    return render(request, 'edu_progs/program_order_success.html', context)

edu_progs/templates/edu_progs/index.html
{% extends 'base.html' %}

{% block title %}
    Учебные программы
{% endblock %}


{% block content %}

    <div class="container1">
        <h1>Учебные программы</h1>

        <div class="theprog">
            {% for prog in progs %}
                {% include 'edu_progs/includes/short_story.html' %}
            {% endfor %}
        </div>

    </div>

{% endblock content %}

edu_progs/templates/edu_progs/program_detail.html
{% extends 'base.html' %}

{% block title %}
  Учебные программы
{% endblock %}

{% block content %}
    <div class="program_detail">
        <h1 class="progName">{{ program.name }}</h1>
        <h3 class="progH3">{{ program.description |safe }}</h3>
        {% load thumbnail %}
        <div style="text-align: center;">
            {% thumbnail program.image "800" crop="center" upscale=True as im %}
                <img class="program_detail_img" src="{{ im.url }}">
                <!-- <img class="program_detail_img" src="https://int.world-camps.org/wp-content/uploads/2022/07/IMG-Tennis-Girls-photo-2.jpg"> -->
            {% endthumbnail %}
        </div>

        <div class="endRegistration">
            Конец регистрации: <span>{{ program.reg_end }}</span> 
        </div>
        

        {% if program.is_free %}
            Программа бесплатна
        {% endif %}
        <div class="prog_discript_sh">
            {{ program.text |safe }}
        </div>

        <div class="progFormLink">
            <a href="{% url 'edu_progs:program-form' program.id %}">Заполнить форму</a>
        </div>
        
    </div>
{% endblock content %}

edu_progs/templates/edu_progs/program_form.html
{% extends 'base.html' %}

{% block title %}
  Учебные программы
{% endblock %}

{% block content %}
    <div class="program_detail">
        <h1 class="formProgName">{{ program.name }}</h1>

     {% load user_filters %}
              {% if form.errors %}   
        <div class="danger_style" style="margin-bottom: 30px;">
      
          <div class="alert alert-danger">
            
               {% for field in form %}
                {% for error in field.errors %}
                  {{ error }} 
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                {{ error }}
              {% endfor %}
              
          </div>

        </div>
    {% endif %}

        <form method="post" enctype="multipart/form-data" action="">
          <input type="hidden" name="csrfmiddlewaretoken" value="">
          {% csrf_token %}
          {% for field in form %}
              <div class="form-group row my-3 p-3 program_form">
                <label for="{{ field.id_for_label }}">
                  {{ field.label }}
                  {% if field.field.required %}
                    <span class="required text-danger">*</span>
                  {% endif %}
                </label>
                <br>
                {{ field|addclass:'form-control' }}
                {% if field.help_text %}
                  <small
                     id="{{ field.id_for_label }}-help"
                     class="form-text text-muted"
                  >
                    {{ field.help_text|safe }}
                  </small>
                {% endif %}
              </div>
          {% endfor %}
          <div class="d-flex justify-content-end submit-btn">
            <button type="submit" class="btn btn-primary">
              {% if is_edit %}
                Сохранить
              {% else %}
                Добавить
              {% endif %}
            </button>
          </div>
        </form>
    </div>
{% endblock content %}

edu_progs/templates/edu_progs/program_order_success.html
{% extends 'base.html' %}

{% block title %}
  Учебные программы
{% endblock %}

{% block content %}
    <div class="program_detail">
        <h1>Ваша заявка принята!</h1>
    </div>
{% endblock content %}